version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "-"
