version: '3'

services:
  frontend-app:
    image: foodanddrinkreact:latest
    container_name: foodanddrink-react
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./front-end:/app
    build:
      context: ./front-end
      dockerfile: Dockerfile
